version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: evolution-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: evolution-api-saas
    volumes:
      - mongodb_data:/data/db
    networks:
      - evolution-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evolution-api-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/evolution-api-saas?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE: 7d
      EVOLUTION_API_URL: https://evo.wcpilot.me
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - evolution-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: evolution-api-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NEXT_PUBLIC_APP_NAME: Evolution API SAAS
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - evolution-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: evolution-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - evolution-network

volumes:
  mongodb_data:

networks:
  evolution-network:
    driver: bridge